Traceback (most recent call last):
  File "results.py", line 320, in <module>
    train(model_args)
  File "/home/jonas/ucloud/thesis/code/self-supervised-ids/main_trans.py", line 327, in main
    finetuner.evaluate()
  File "/home/jonas/ucloud/thesis/code/self-supervised-ids/classes/trainer.py", line 232, in evaluate
    self.stats.save_stats()
  File "/home/jonas/ucloud/thesis/code/self-supervised-ids/classes/statistics.py", line 447, in save_stats
    self.class_stats.save_stats()
  File "/home/jonas/ucloud/thesis/code/self-supervised-ids/classes/statistics.py", line 183, in save_stats
    n_attack = self.n_samples - self.number[self.benign]
KeyError: 10
Error in run transformer_flows15_rn500_do00_nl10_nh3_fx2_bs1024_lr001_tep50_tp100_sp0_sep0_xyNONE